# Generated by Django 5.2.6 on 2025-09-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_researcherprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherprofile',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='approved',
        ),
    ]
