# Generated by Django 5.2.6 on 2025-09-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_researcherprofile_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
